package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/oscillatelabsllc/engram/internal/api"
	"github.com/oscillatelabsllc/engram/internal/db"
	"github.com/oscillatelabsllc/engram/internal/dreamer"
	"github.com/oscillatelabsllc/engram/internal/embedding"
	"github.com/oscillatelabsllc/engram/internal/llm"
	"github.com/oscillatelabsllc/engram/internal/mcp"
	"github.com/oscillatelabsllc/engram/internal/proxy"
)

func main() {
	subcmd := "serve"
	args := os.Args[1:]
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		subcmd = args[0]
		args = args[1:]
	}

	switch subcmd {
	case "serve":
		runServe(args)
	case "stdio":
		runStdio()
	default:
		fmt.Fprintf(os.Stderr, "Unknown subcommand: %s\n", subcmd)
		fmt.Fprintf(os.Stderr, "Usage: engram [serve|stdio]\n")
		fmt.Fprintf(os.Stderr, "  serve   Start the HTTP/SSE server (default)\n")
		fmt.Fprintf(os.Stderr, "  stdio   Stdio proxy to a running server\n")
		os.Exit(1)
	}
}

func runServe(args []string) {
	fs := flag.NewFlagSet("serve", flag.ExitOnError)
	port := fs.String("port", "", "HTTP server port (default: 3490, env: ENGRAM_PORT)")
	fs.Parse(args)

	resolvedPort := "3490"
	if envPort := os.Getenv("ENGRAM_PORT"); envPort != "" {
		resolvedPort = envPort
	}
	if *port != "" {
		resolvedPort = *port
	}

	dbPath := os.Getenv("DUCKDB_PATH")
	if dbPath == "" {
		dbPath = filepath.Join(".", "engram.duckdb")
	}

	embeddingURL := os.Getenv("EMBEDDING_URL")
	if embeddingURL == "" {
		// OLLAMA_URL is deprecated; kept for backward compatibility
		embeddingURL = os.Getenv("OLLAMA_URL")
	}
	if embeddingURL == "" {
		embeddingURL = "http://localhost:11434"
	}

	embeddingModel := os.Getenv("EMBEDDING_MODEL")
	if embeddingModel == "" {
		embeddingModel = "nomic-embed-text"
	}

	embeddingAPIKey := os.Getenv("EMBEDDING_API_KEY")

	// Dreamer LLM configuration
	llmEndpoint := os.Getenv("ENGRAM_LLM_ENDPOINT")
	if llmEndpoint == "" {
		llmEndpoint = "http://localhost:11434/v1"
	}

	llmModel := os.Getenv("ENGRAM_LLM_MODEL")
	if llmModel == "" {
		llmModel = "qwen3:8b"
	}

	llmAPIKey := os.Getenv("ENGRAM_LLM_API_KEY")

	llmTimeout := dreamer.DefaultLLMTimeout
	if v := os.Getenv("ENGRAM_LLM_TIMEOUT"); v != "" {
		d, err := time.ParseDuration(v)
		if err != nil {
			log.Fatalf("Invalid ENGRAM_LLM_TIMEOUT %q: %v", v, err)
		}
		llmTimeout = d
	}

	llmAdapter := os.Getenv("ENGRAM_LLM_ADAPTER")
	if llmAdapter == "" {
		llmAdapter = "openai"
	}

	claudeBin := os.Getenv("ENGRAM_CLAUDE_BIN")
	if claudeBin == "" {
		claudeBin = "claude"
	}

	var dreamInterval time.Duration
	if v := os.Getenv("ENGRAM_DREAM_INTERVAL"); v != "" {
		d, err := time.ParseDuration(v)
		if err != nil {
			log.Fatalf("Invalid ENGRAM_DREAM_INTERVAL %q: %v", v, err)
		}
		dreamInterval = d
	}

	var llmClient dreamer.LLM
	switch llmAdapter {
	case "openai":
		llmClient = llm.NewClient(llmEndpoint, llmModel, llmAPIKey, llmTimeout)
	case "claude-cli":
		llmClient = llm.NewClaudeCLI(claudeBin)
	default:
		log.Fatalf("Unknown ENGRAM_LLM_ADAPTER %q: must be 'openai' or 'claude-cli'", llmAdapter)
	}

	store, err := db.NewStore(dbPath)
	if err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	embedder := embedding.NewClient(embeddingURL, embeddingModel, embeddingAPIKey)
	dreamWorker := dreamer.New(store, llmClient, embedder, llmTimeout)

	fmt.Fprintf(os.Stderr, "===================================\n")
	fmt.Fprintf(os.Stderr, "Engram memory system starting...\n")
	fmt.Fprintf(os.Stderr, "Mode: serve\n")
	fmt.Fprintf(os.Stderr, "Database: %s\n", dbPath)
	fmt.Fprintf(os.Stderr, "Embedding endpoint: %s\n", embeddingURL)
	fmt.Fprintf(os.Stderr, "Embedding model: %s\n", embeddingModel)
	fmt.Fprintf(os.Stderr, "LLM adapter: %s (model: %s)\n", llmAdapter, llmClient.Model())
	if dreamInterval > 0 {
		fmt.Fprintf(os.Stderr, "Dream interval: %s\n", dreamInterval)
	} else {
		fmt.Fprintf(os.Stderr, "Dream interval: disabled (trigger via POST /api/v1/admin/dream)\n")
	}
	fmt.Fprintf(os.Stderr, "Port: %s\n", resolvedPort)
	fmt.Fprintf(os.Stderr, "===================================\n")
	fmt.Fprintf(os.Stderr, "\nMCP SSE endpoint: http://localhost:%s/mcp/sse\n", resolvedPort)
	fmt.Fprintf(os.Stderr, "Health check:     http://localhost:%s/health\n\n", resolvedPort)

	// Stale embeddings (model swap or past embedding failures) silently
	// degrade vector search — warn loudly, but leave re-embedding as a
	// deliberate operator action.
	warnCtx, warnCancel := context.WithTimeout(context.Background(), 10*time.Second)
	if stale, err := store.CountReembedTargets(warnCtx, embeddingModel, false); err == nil && stale.Total() > 0 {
		fmt.Fprintf(os.Stderr, "WARNING: %d stored embeddings (%d episodes, %d entities, %d knowledge) are missing or were generated by a different model than %q.\n",
			stale.Total(), stale.Episodes, stale.Entities, stale.Knowledge, embeddingModel)
		fmt.Fprintf(os.Stderr, "         Vector search quality degrades when embedding spaces are mixed.\n")
		fmt.Fprintf(os.Stderr, "         Refresh them with: curl -X POST http://localhost:%s/api/v1/admin/reembed\n\n", resolvedPort)
	}
	warnCancel()

	mcpServer := mcp.NewServer(store, embedder)
	apiServer := api.NewServer(store, embedder, dreamWorker, resolvedPort)
	apiServer.AddMCPServer(mcpServer.GetMCPServer())

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	// Optional automatic dreaming: trigger the same job runner as the admin
	// endpoint on a fixed interval, skipping ticks while a job is running
	if dreamInterval > 0 {
		ticker := time.NewTicker(dreamInterval)
		go func() {
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if err := apiServer.TriggerDream(ctx); err != nil && !errors.Is(err, api.ErrDreamRunning) {
						fmt.Fprintf(os.Stderr, "Warning: scheduled dream did not start: %v\n", err)
					}
				}
			}
		}()
	}

	// The process must not exit before store.Close() completes — DuckDB
	// checkpoints its WAL on close, and an unflushed WAL containing the
	// startup migration DDL can fail to replay on the next boot.
	shutdownDone := make(chan struct{})
	go func() {
		<-ctx.Done()
		fmt.Fprintf(os.Stderr, "\nShutting down...\n")
		if err := apiServer.Shutdown(context.Background()); err != nil {
			fmt.Fprintf(os.Stderr, "Shutdown error: %v\n", err)
		}
		store.Close()
		close(shutdownDone)
	}()

	if err := apiServer.Serve(); err != nil {
		log.Fatalf("Server error: %v", err)
	}
	// Serve returns nil only after Shutdown() was initiated by the signal
	// handler above — wait for it to finish closing the store.
	<-shutdownDone
}

func runStdio() {
	serverURL := os.Getenv("ENGRAM_SERVER_URL")
	if serverURL == "" {
		serverURL = "http://localhost:3490"
	}

	fmt.Fprintf(os.Stderr, "Engram stdio proxy connecting to %s...\n", serverURL)

	if err := proxy.RunStdioProxy(serverURL); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
